version: '3.9'

services:
    mysql-db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - 33060:3306
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: StudioManagementSystem
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_HOST: localhost

    frontend:
        container_name: frontend
        build:
            context: ./src/frontend
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - mysql-db
