version: '3.9'

networks:
    sms-network:
        driver: bridge

volumes:
    database:

services:
    maria-db:
        # https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8
        # Maria db is cross compatible with ARM (M1 Apple)
        # this Dockerfile is separate because it causes issues in the multistage build process for unknown reasons
        # which is fine anyway, this keeps the build time faster as we can setup the dependency with a small Dockerfile
        container_name: maria-db
        build:
            context: ./database
        volumes:
            - database:/var/lib/mysql
        ports:
            - 33060:3306
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: StudioManagementSystem
            MYSQL_USER: admin_user
            MYSQL_PASSWORD: super_secret_password
            MYSQL_ROOT_PASSWORD: super_secret_root_password
            MYSQL_HOST: localhost

    backend_api:
        container_name: backend_api
        build:
            context: ./src/server
        ports:
            - 7320:7320
        networks:
            - sms-network
        restart: unless-stopped

    nginx-revproxy:
        container_name: nginx-revproxy
        build:
            context: ./src/frontend
        volumes:
            - ./.certs:/data/certs
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        networks:
            - sms-network
        depends_on:
            - maria-db
