version: '3.9'

services:
    maria-db:
        # https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8
        # Maria db is cross compatible with ARM (M1 Apple)
        container_name: maria-db
        build:
            context: ./database
            dockerfile: Dockerfile
        ports:
            - 33060:3306
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: StudioManagementSystem
            MYSQL_USER: admin_user
            MYSQL_PASSWORD: super_secret_password
            MYSQL_ROOT_PASSWORD: super_secret_root_password
            MYSQL_HOST: localhost

    frontend:
        container_name: frontend
        build:
            context: ./src/frontend
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - maria-db

# create an internal docker network for our application stack
networks:
    default:
        name: sms-network
