version: '3.9'

# create an internal docker network for our application stack
networks:
    default:
        name: sms-network

# custom
volumes:
    database:
    letsencrypt:

services:
    maria-db:
        # https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8
        # Maria db is cross compatible with ARM (M1 Apple)
        # this Dockerfile is separate because it causes issues in the multistage build process for unknown reasons
        # which is fine anyway, this keeps the build time faster as we can setup the dependency with a small Dockerfile
        container_name: maria-db
        build:
            context: ./database
            dockerfile: Dockerfile
        volumes:
            - database:/var/lib/mysql
        ports:
            - 33060:3306
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: StudioManagementSystem
            MYSQL_USER: admin_user
            MYSQL_PASSWORD: super_secret_password
            MYSQL_ROOT_PASSWORD: super_secret_root_password
            MYSQL_HOST: localhost

    nginx-revproxy:
        # this revproxy exposes the application securely
        # the react-app and .NET backend are exposed internally on this stack's docker network rather than exposing their ports directly
        # see: https://nginxproxymanager.com/guide/
        container_name: nginx-revproxy
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./nginx:/data
            - letsencrypt:/etc/letsencrypt
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        environment:
            DISABLE_IPV6: 'true'
            # use the existing mariadb service rather than inbuilt sqlite db
            DB_MYSQL_HOST: 'maria-db'
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: 'npm_user'
            DB_MYSQL_PASSWORD: 'super_secret_password'
            DB_MYSQL_NAME: 'NginxProxyManager'
        depends_on:
            - maria-db
        # opt in to enable the npm health check
        healthcheck:
            test: ['CMD', '/bin/check-health']
            interval: 30s
            start_period: 20s
            timeout: 10s
