version: '3.9'

services:
    mysql-db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - 33060:3306
        restart: unless-stopped
    frontend:
        container_name: frontend
        build:
            context: ./src/frontend
            dockerfile: Dockerfile
        volumes:
            - '.:frontend/src/'
            - 'frontend/src/node_modules'
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - mysql-db
