// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudioManagementSystem.Core;

#nullable disable

namespace StudioManagementSystem.Core.Migrations
{
    [DbContext(typeof(StudioManagementDbMigrationContext))]
    [Migration("20230507152251_Update_GroupApplications_WithOneToManyRelationship")]
    partial class Update_GroupApplications_WithOneToManyRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProductOwnersToManagedProducts", b =>
                {
                    b.Property<Guid>("ManagedProductsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductOwnersId")
                        .HasColumnType("char(36)");

                    b.HasKey("ManagedProductsId", "ProductOwnersId");

                    b.HasIndex("ProductOwnersId");

                    b.ToTable("ProductOwnersToManagedProducts");
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("contact_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contact", (string)null);

                    b.HasDiscriminator<string>("contact_type").HasValue("Contact");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedProjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedProjectId");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.GroupApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("");

                    b.Property<Guid>("StudentContactId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentContactId");

                    b.ToTable("GroupApplication", (string)null);
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.GroupProjectPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("GroupProjectPreference", (string)null);
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PrincipalOwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalOwnerId");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.OwnerContact", b =>
                {
                    b.HasBaseType("StudioManagementSystem.Core.Entities.Contact");

                    b.Property<string>("StudioSection")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("ownercontact");
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.StudentContact", b =>
                {
                    b.HasBaseType("StudioManagementSystem.Core.Entities.Contact");

                    b.Property<Guid?>("AssignedGroupId")
                        .HasColumnType("char(36)");

                    b.HasIndex("AssignedGroupId");

                    b.HasDiscriminator().HasValue("studentcontact");
                });

            modelBuilder.Entity("ProductOwnersToManagedProducts", b =>
                {
                    b.HasOne("StudioManagementSystem.Core.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ManagedProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioManagementSystem.Core.Entities.OwnerContact", null)
                        .WithMany()
                        .HasForeignKey("ProductOwnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.Group", b =>
                {
                    b.HasOne("StudioManagementSystem.Core.Entities.Project", "AssignedProject")
                        .WithMany("AssignedGroups")
                        .HasForeignKey("AssignedProjectId");

                    b.Navigation("AssignedProject");
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.GroupApplication", b =>
                {
                    b.HasOne("StudioManagementSystem.Core.Entities.Group", "Group")
                        .WithMany("MemberApplications")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioManagementSystem.Core.Entities.StudentContact", "StudentContact")
                        .WithMany("GroupApplications")
                        .HasForeignKey("StudentContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("StudentContact");
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.GroupProjectPreference", b =>
                {
                    b.HasOne("StudioManagementSystem.Core.Entities.Group", "Group")
                        .WithMany("GroupProjectPreferences")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioManagementSystem.Core.Entities.Project", "Project")
                        .WithMany("GroupProjectPreferences")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.Project", b =>
                {
                    b.HasOne("StudioManagementSystem.Core.Entities.OwnerContact", "PrincipalOwner")
                        .WithMany("PrincipalProjects")
                        .HasForeignKey("PrincipalOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrincipalOwner");
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.StudentContact", b =>
                {
                    b.HasOne("StudioManagementSystem.Core.Entities.Group", "AssignedGroup")
                        .WithMany("Members")
                        .HasForeignKey("AssignedGroupId");

                    b.Navigation("AssignedGroup");
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.Group", b =>
                {
                    b.Navigation("GroupProjectPreferences");

                    b.Navigation("MemberApplications");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.Project", b =>
                {
                    b.Navigation("AssignedGroups");

                    b.Navigation("GroupProjectPreferences");
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.OwnerContact", b =>
                {
                    b.Navigation("PrincipalProjects");
                });

            modelBuilder.Entity("StudioManagementSystem.Core.Entities.StudentContact", b =>
                {
                    b.Navigation("GroupApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
